### ISSUE TITLE
image rotate Counter-Clockwise 90 degree under iPhone

### ISSUE THREAD

**Issue by Eric0329** [VenRaaS/TITAN#5]
image rotate Counter-Clockwise 90 if using `keras.preprocessing.load_img()`

**Comment by robinsu** [comment]
original file capture by iPhone:
https://www.dropbox.com/s/yufmzqe1xos4hax/IMG_1357.JPG?dl=0
https://www.dropbox.com/s/mhhm7g43f0rs0es/IMG_1358.JPG?dl=0

**Comment by robinsu** [comment]
![image](https://user-images.githubusercontent.com/129440/40907091-49cb55d8-6815-11e8-9402-904cf605a7bb.png)

**Comment by robinsu** [comment]
after simple testing, "opencv2.imread" can read iphone image to right rotation. 
`
import cv2
import numpy as np
from matplotlib import pyplot as plt

img6 = cv2.imread('IMG_1358.JPG')
plt.imshow(cv2.cvtColor(img6, cv2.COLOR_BGR2RGB))
`
![image](https://user-images.githubusercontent.com/129440/41214107-f78fe1a0-6d7b-11e8-89ed-b6f5b33a26b4.png)

**Comment by Eric0329** [comment]
https://github.com/VenRaaS/TITAN/commit/b5e95c25f5ca4885fcf346697f84d84c743b96d0#diff-a1ba11958ef6764672965d9c58823141R29

**Comment by Eric0329** [comment]
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAUgAAACaCAMAAAD8SyGRAAABKVBMVEX////u7u7z8/P5+fn19fX8/Pzt7e339/fq6urm5ub///n//vz/+vPz7ObT4On8///bzsGvr67b29mioaHm7PLz+v+NiYeZlpm1rafa292Toa7P0NCopKHo8Pr///fHycfv5NfUzsjLw7bFvriqrrLx5uD/9+iXkZDN2+vY09aeoaionZ/Ar6elqba5ubTIzcuakoa7ubx6cHJ8hY7Ey9m2wMW8wsro2cyQhn2qsa6jqq5sbHWtt8K7s6u1q7LNu66ipbSAgIayppqzwdPl9f+jnpmsoJCFlKHK0dm3wLyXorTWx7uKjZDJw8WMeW2Hdnx3fpJrXltbZnlEQ0deWF9scn6dkn90ZVtoZGJ7jaF0dHWrmZJqb3q4rJhkVUp+gIt9Z21zc4iOjZw7bS+GAAAMNklEQVR4nO1dCVviyBa9WSDELEASlhAQwtIo09oubKPhOWArGUXH6Wlt22lfv5n//yNeBdC2JQkYlUCs87EmdevUPVQqVTdFCgADAwMDAwMDAwMDAwMDAwMDAwMDAwMDY7646iZvTOsDXx5+T0PfNl1LHH/YsV648s97hcwrFW95cJWAwlcoyUrsm6LLZuVabVrfhLyM5OXyWbNTBkFuwFYmlJYVSMe7aLfY2keJm0hAE3SlJJvvMoIITdBlcTpjQHE1kG/M04ywzw4qGW6H3Fm9sL5VLsnrBPCfiS/msbij9JrvzY7Z6h8YrUvJED6TA6FP7SjAf4MdaY++ETKxJndZ2KV3En475BeuxNg36ImwpdZWqqnrRBsubkW40gzYQkL24Q840PZluXEgtpLV/t85SPJJeZ8bcCixAnCcz/DJ1H4FCQm7xV25qvjtkF+4ysHtiVUHid1ihv8zcT6qkYUNaCMhd5GQt6hGFusHzXMxhmpk4bKDaiTXPe2vfEGiFf4SDwz+cyXTyhQ+tfpc8s3WSD0BXNxqFWFT3Sznc7o5aiNNyCMhNTgDKSdky1GhzMrNJnTK2kq2nE+UrMRW7dsGPl3OEybaY7WRpt/+YGAEHRxpu5l88E48TK4SIXuLiQzvzYgH+d2BDgEw1I+cGeZh6mWEYNhtjV2O3vk9GPetxziuHQn2XfE7VO52/xkdf6hBdeXiUarjNdTuiud3SaB4CPeplxNCXT/qDvvHLbm7nTR4OWkAfzMAWK1Bq7mNOjtd6A3qkEbbQbg20sIJXx0oAnoClJJmJ9lAbxtof5OXu2wymVmpDkRkhvQv5VrN1fJ261rar9aQaPFqLd1VhOQgcTsYKC2lDZ0B6q9DLJmso62UDJVGGY6S5g+GpUHhpFdHYxaEWAb1m7uVXWgrbQIJCe2PV2rqfV24jGWoL/kMtJHeW4lz4eQYbesYkvVVbH0NtbXvkC6dQFu6jJ7nYpnbQ7T7kN9HWRrHF63Gd0iufIK/UfKdxHE91jjPFb7eHr67OF1rS33qPAer+9Cr7yinmWOxp16cGivlXlPY72xUlmkAVNjoKe9GQjb5fyFZycD7X/er13W0Ye/7as3qW3cG8Xi6Dgd1S8i2cHK1Fy+T8Zum9TW2G48XTyDUqUPvQwb+B3zm71q8jGRDxy0/SP2STHyHATq0UW8evsPtx1bjD+D+uV2Df4pr7dIgnlUA8ceaN/F4o1Droo7+GlBXtSGDbbOzoEA1UnmHWjChORbyk3aToIQuOhBX/lvnB7F+8Vvhu3QjfJOuc+MaeZDRv94aSD7YyqHtO5Eb9Vq6lPZR63ls9PqnfX23tVv8jHI/Pzn9BJeww46EvITjjy3jyuid3PZLmeLauWWN+uZfzPP6VrO3AV8MuCjs6qjTr18cGEX31nixQCksxanoNKoKCnpnK/1hB5q19klRjgXJZKGCtglnw+1RKcSCno+Crg2/gjDeVzlLoNSgq8gE7bbM0M9D8iyoILEqRNB5GeWf4BXQTYhIeRAS0tAandPOVAXyKEM2YaU+Swyz0LSoS8EXHfZncQwMDAyMN4ow4RnPMCUiy0cbchfyGaN7mvJuGzza4HnkE23wPPKJNnge+US7UB4xjzAn2pmwTEIS5CPYpnpxWmp8XrYIrVfC9gdcIiHpoXg0SSOQ489zoA2Nfz+CJu8+2TEskZAj7SiSoSjmrk7OixYhjDrVz/j9Fk3IR5gjLUGSxDNoF0nIiTZyPkJONs1LLmSYDFE/ITSnGjnBsORCTno0pxr5IrRYyOAJOdk00eE50C6YkKEhULvmiKm0YS9CMpQdUPeJsrpSDGk1te60CyUkOQoShhGcI3oPS/JCNdLqTA9ZHfHzSGXRhRwNDGzrxhhoqEI/pHqhNpKk7btI96CGRbuvk4su5HCYah9iGGPo0IOizHZoT/WIcOhr/sz7g3g5hHSLxTOvI6RTp/0eb1JID4c2rpFzFBK1z1jIt1cj6alCEq8jZHiqkMxSCUlNEZIKMz/FS1+q+0MA4eoBNeyZB0pIgMi0IYaHGskA9daERMf2KxzahH3w8Afvsgk5vY18nZPNDCMbeqmExGftlzq0aSykZwS2RtJ2ybCQyyekW9qhQw9SYCFtsx7FI52D46HQK8Uj6SGxG4ifiBf+KuJwyswwRE44BMnJ6RFyLxe/rGkmDgH5SCQy4n2QyYxXOHyrkcNLNtb1GvSknK7bTKX16SriYgn5VCyQkDaXirCQnmgXqB/5dCy0kHjKikfax5c8bSe4LpWQY4Qjc52NNnHaX/5DezyrjgmF5yrkJDzQLpKQ4wnPP6bOzlXI4UFN0QEQEsJjJYnx3E+asBu+vzQtNTm/lfZAu0hChu78uBPUNgzy4rT0RBvphXaRhPSN1mUINjPtYnm0xLTB88gn2uB55BNt8DzyiTZ4HvlEGwb76OF0AOkyYXya7TLSugsZmeiNzoyIzT+1ZgW7fLTBO7Sn3KXjtWiDJ+Ri0gbPI59og+eRT7QvnbUkqB+k4acm6DkAoaZ6peUas9KuipquDu/uXooCVBSAVg4km9u9O9HmrXucD7HtVJp5C7mlm9kuKzf1IwNKbNbo/dq1u3+jPa0uGy3ZLMqynDWLWbVsm8iGttDPl1Jmp0bKO1GumlXklD4wjm3u9/6IlmtU1CMZlTZfkWvWIhoVeaDLebPDbMu1R8Wet5Cblcbv271yagPKUOrUUnnFVg572oOPaRnk7EpDT/yn1DHsa4cN7bvDdGm7sptO5d5HVzZav4qnv+fixdxUWq5cMRvv9uTm5i8Qb29uAHpDBYhv1T7UH5vPW8hOqdGolsrldHwDSlpN1nO2Kyo4CtmJGzJvCVntbMxcI1f/jSPeVFar7URXfouZcnITCVmfTls9MrvZfDkVL5X7nc0mnO4NUAEOzH3BdyFHoIYP9JM/nfY+U6fuojNtaGwj7KWi9hlM0lpLFFFwX2LqQQFmpXXKemYs6OkTgXG6ra4N7azd+zcppB+0wfPIJ9rgeeQT7RJ65E/QgpniLes0T3MqyEjYu+0S0k4N7HrGc2qkT7T40F582uB55BNt8DzyidbKmgSaBYg8td1yz5qdSuuESNTV2I2WmmLsTMuxECYo0vnPQrMIqQupfKZl9J64FJFr1qXtjWm0Djg19kqbLquPONNybTFm7HVcjJ1pj0rGWftDLeW4ZuUsQnbSH6HHpspPXPjSNeu4+/plLkIeiNWam7EzLaWLrcFeHH7zQhurr2YKa7rjAmGzCJkurUE1n2gduid9UtZZz0JW8rLsTUiIib1o1s3YmbZoQFEsTATPZqK9z1qHjizycu0la6Tgvmizi5BC1hRkl5XjXGgriiC7GjvTpmVTi0LauVXAZ+050QbPI59og+eRT7TB88gn2uB55BPtK0boXol2UeORXgN01j/LvdsuHy2La+TL0E7zNniNlU+0wfPIJ9rgeeQT7TDr0miUba0sDLwJwmzxNNesebfhsqtHfFZ0NXYdayNjoeZlrK3LRDwulppeaO+zXjky+LhBxlN6WS+HVf3IZkLcU7PORr1Gf94n0ilv0R+hLcbMWnbFS/TnbPUEjqR651nRn1jmplIvpaLZLLPH//L7RuEFhPQejyzUBh7jkdAST8t7e+AcUnahrSYKh8+NR1ajMXmtFM+nZEiV4o1Ux2ZC3FOz7uS9RshbH2qdvKcIOcTEA7OWdjF2pj03lPcfhdrRsyLkJECYYoAlaWBYYJhpfc+ZspZcF1p3a/XZkKux22xCCiT08EIbsbyHiHMCfNaeE23wPPKJNnge+UQbPI98og2eRz7RRtyW83GH+1JA7lhC2ilCMjQ9fMzwMrGF8WI0tmSebjR+Gdl6sRzZPtXo7sV7ZcbAwMBYCjzjIgXGA5xJCsdwMLynMjBI1nUGJIligGPQ8F5I0MBJCWodaE5Bo3br7EIDFQoxoWd0uAIJTSM1aT2haZKmalpEAV1C75Kq6hrJqFJE0jSNVTVJYtUztFkDSZWsr5rmd8kXC7zKa6pwRmvrgkKcSSzAOqci1RISm08IChItr1akxLpESeq6cKaqoEV1RUKJ1v0u+oKBVamIykkRAtBTpRQIcyQbkVQyotIsR5JqOKKGJEVXQ+QZy0lkmFJpiSVCxDP+zPKGMPFXWnL8xMDAwMDAwMDAeIj/A7d0PSlmLogEAAAAAElFTkSuQmCC

**Comment by Eric0329** [comment]
![image](https://user-images.githubusercontent.com/3777869/41580744-854a47ee-73ce-11e8-8bf0-c47e0b6a3bb0.png)
