### ISSUE TITLE
image aspect ratio distortion while image load with target_size parameter

### ISSUE THREAD

**Issue by Eric0329** [VenRaaS/TITAN#6]
aspect ratio distortion 
`image.load_img(imgFP, target_size=(224, 224))`

**Comment by robinsu** [comment]
![image](https://user-images.githubusercontent.com/129440/40906934-e03f527c-6814-11e8-8d95-2fb12b49f280.png)

**Comment by Eric0329** [comment]
![image](https://user-images.githubusercontent.com/3777869/41268351-34a3cbae-6e32-11e8-82cb-fa5d9561b4bc.png)

**Comment by Eric0329** [comment]
![image](https://user-images.githubusercontent.com/3777869/41268711-11f3074e-6e34-11e8-9d26-af52f86bb085.png)

**Comment by Eric0329** [comment]
![image](https://user-images.githubusercontent.com/3777869/41275407-6af0f1f2-6e53-11e8-8446-279526e139aa.png)

**Comment by Eric0329** [comment]
https://github.com/VenRaaS/TITAN/commit/b5e95c25f5ca4885fcf346697f84d84c743b96d0#diff-a1ba11958ef6764672965d9c58823141R33
